### ISSUE TITLE
12 hour clock still displays as 24 hours

### ISSUE THREAD

**Issue by oparada1988** [StreamController/Clocks#1]
When disabling the 24 hour clock, it still displays time in military

![Screenshot from 2024-04-10 20-50-23](https://github.com/StreamController/Clocks/assets/4031078/e96d6e9a-4594-43df-9b50-8cf08edc4777)

**Comment by Core447** [comment]
Fixed with 8f60ed32de06001dd818c39362cb2d44eb695229
